## Functions {data-progressive=FALSE}

This list of functions and their descriptions is a useful starting point and overview of 
what is available to you through the xgxr package for making plots similar to those 
on the xGx website.

This will be a good reference for the next section, which will go over how to use many of these functions.

### Tabulation
  - [xgx_check_data()](https://www.rdocumentation.org/packages/xgxr/versions/1.0.9/topics/xgx_check_data)
      - Provides summary tables to check your data
  - [xgx_summarize_covariates()](https://www.rdocumentation.org/packages/xgxr/versions/1.0.9/topics/xgx_summarize_covariates)
      - Summarizes covariate information

### Plots and Themes
  - [xgx_theme()](https://www.rdocumentation.org/packages/xgxr/versions/1.0.9/topics/xgx_theme)
      - Sets the global theme to the Novartis xGx theme for plots
  - [xgx_plot()](https://www.rdocumentation.org/packages/xgxr/versions/1.0.9/topics/xgx_plot)
      - Constructs a plot with the Novartis xGx theme

### Confidence Intervals and Smooths
  - [xgx_geom_ci()](https://www.rdocumentation.org/packages/xgxr/versions/1.0.9/topics/xgx_geom_ci)
    - Plot mean & confidence intervals under different 
      distribution assumptions (binomial, normal, lognormal, etc.)
    - This function now has binning capabilities and ordinal compatibility. 
      [See new source code version here](https://github.com/Novartis/xgxr/blob/master/R/xgx_stat_ci.R)
  - [xgx_geom_pi()](https://www.rdocumentation.org/packages/xgxr/versions/1.0.9/topics/xgx_geom_pi)
    - plot median & percentile intervals
  - [xgx_geom_smooth()](https://github.com/Novartis/xgxr/blob/master/R/xgx_stat_smooth.R)
    - Plot the mean & confidence intervals of a model which fits the data.  
      Aids the eye in seeing patterns in the prescence of overplotting.
    - This function now has ordinal compatibility via supplying `method="polr"` as a parameter.

### Scaling
  - [xgx_scale_y_log10()](https://www.rdocumentation.org/packages/xgxr/versions/1.0.9/topics/xgx_scale_y_log10)
    - Change y axis to log10 scale, niceley spaced major & minor gridlines
  - [xgx_scale_x_time_units()](https://www.rdocumentation.org/packages/xgxr/versions/1.0.9/topics/xgx_scale_x_time_units)
    - Convert time units for plotting
  - [xgx_scale_y_reverselog10()](https://www.rdocumentation.org/packages/xgxr/versions/1.0.9/topics/xgx_scale_y_reverselog10)
    - Scale y axis nicely for receptor occupancy data, increases resolution around 100%
  - [xgx_scale_y_percentchange_log10()](https://www.rdocumentation.org/packages/xgxr/versions/1.0.9/topics/xgx_scale_y_percentchange_log10)
    - Scale y axis nicely for percent change data, increases resolution around -100%

### Saving and Annotation
  - [xgx_annotate_status()](https://www.rdocumentation.org/packages/xgxr/versions/1.0.9/topics/xgx_annotate_status)
    - Add a draft status watermark
  - [xgx_annotate_filenames()](https://www.rdocumentation.org/packages/xgxr/versions/1.0.9/topics/xgx_annotate_filenames)
    - Add metadata to the bottom of a figure
  - [xgx_save()](https://www.rdocumentation.org/packages/xgxr/versions/1.0.9/topics/xgx_save)
    - save figures with status and metadata watermarks
  - [xgx_save_table()](https://www.rdocumentation.org/packages/xgxr/versions/1.0.9/topics/xgx_save_table)
    - Saves table to csv, with source metadata

### Automated Template Construction
  - [xgx_auto_explore()](https://github.com/Novartis/xgxr/blob/master/R/xgx_auto_explore.R)
    - Creates a folder in the current working directory containing an xGx template applied to a new user-provided dataset