---
title: "Tutorial for the xGx package"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  learnr::tutorial:
    progressive: True
    allow_skip: False
  html_document:
    toc: true
    toc_float: true
    self_contained: no

runtime: shiny_prerendered
---

```{r setup, include=FALSE}

# xgxr and xgx github raw script url location
xgxr_master_url = "https://raw.githubusercontent.com/Novartis/xgxr/master/"
xgx_master_url = "https://raw.githubusercontent.com/Novartis/xgx/master/"
xgx_chase_url = "https://raw.githubusercontent.com/Novartis/xgx/chase/"

# Standard packages and xgxr
library(learnr)
library(gridExtra)
library(tidyverse)
library(xgxr)
library(DescTools)
library(minpack.lm)
library(Deriv)
# Add new functions that have not yet been pushed to DaVinci system
source(paste0(xgxr_master_url, "R/xgx_stat_ci.R"))
source(paste0(xgxr_master_url, "R/xgx_stat_smooth.R"))
source(paste0(xgxr_master_url, "R/xgx_auto_explore.R"))

# Set seed for random number generator (for plots with jitter)
set.seed(12345)

# Flag for labeling figures as draft
status = "DRAFT"

# ggplot settings
xgx_theme_set()

# learnr settings
tutorial_options(exercise.timelimit = 60)
knitr::opts_chunk$set(error = TRUE)


pkpd_data <- read.csv(paste0(xgx_master_url, "Data/Multiple_Ascending_Dose_Dataset2.csv"))

# Compartments for PK, dosing, and each PD datatype
DOSE_CMT = 1
PK_CMT = 2
CONTINUOUS_PD_CMT = 3
COUNT_PD_CMT = 4
ORDINAL_PD_CMT = 5
BINARY_PD_CMT = 6

# Steady state days and intervals
SS_PROFDAY = 6
PD_PROFDAYS <- c(0, 2, 4, 6)
# Time between doses, (units should match units of TIME)
#   e.g. 24 for QD, 12 for BID, 7*24 for Q1W (when units of TIME are h)
TAU = 24 

# Ensure dataset has all the necessary columns
pkpd_data = pkpd_data %>%
  mutate(ID = ID,
         TIME = TIME,
         NOMTIME = NOMTIME,
         PROFDAY = case_when(
           NOMTIME < (SS_PROFDAY - 1)*24 ~ 1 + floor(NOMTIME / 24),
           NOMTIME >= (SS_PROFDAY - 1)*24 ~ SS_PROFDAY
         ), #PROFILE DAY day associated with profile, e.g. day of dose administration
         LIDV = LIDV,
         CENS = CENS,
         CMT = CMT,
         DOSE = DOSE,
         TRTACT = TRTACT,
         LIDV_NORM = LIDV/DOSE,
         LIDV_UNIT = EVENTU,
         DAY_label = ifelse(PROFDAY > 0, paste("Day", PROFDAY), "Baseline"),
         ORDINAL_LEVELS = factor(case_when(CMT != ORDINAL_PD_CMT ~ as.character(NA),
                                           LIDV == 1 ~ "Mild",
                                           LIDV == 2 ~ "Moderate",
                                           LIDV == 3 ~ "Severe"),
                                 levels = c("Mild", "Moderate", "Severe")),
         BINARY_LEVELS = factor(case_when(CMT != BINARY_PD_CMT ~ as.character(NA), 
                                          LIDV == 0 ~ "Nonresponder", 
                                          LIDV == 1 ~ "Responder"),
                                levels = c("Nonresponder", "Responder"))
         )

# Create a factor for the treatment variable for plotting
pkpd_data = pkpd_data %>%
  arrange(DOSE) %>%
  mutate(TRTACT_low2high      = factor(TRTACT, levels = unique(TRTACT)),
         TRTACT_high2low      = factor(TRTACT, levels = rev(unique(TRTACT))),
         ORDINAL_LEVELS_low2high    = ORDINAL_LEVELS,
         ORDINAL_LEVELS_high2low    = factor(ORDINAL_LEVELS,
                                             levels = rev(levels(ORDINAL_LEVELS))))

# Create PK and PD datasets
pk_data <- pkpd_data %>%
  filter(CMT == PK_CMT)

# Continuous
continuous_data <- pkpd_data %>%
  filter(CMT == CONTINUOUS_PD_CMT)
# Continuous PD vs PK
continuous_pk_data_wide <- continuous_data %>%
  select(ID, NOMTIME, PD = LIDV) %>%
  right_join(pk_data) %>%
  rename(CONC = LIDV)%>%
  filter(!is.na(PD))%>%
  filter(!is.na(CONC))

# Binary
binary_data <- pkpd_data %>%
  filter(CMT == BINARY_PD_CMT) %>%
  mutate(LIDV_jitter = jitter(LIDV, amount = 0.1))
# Binary PD vs PK
binary_pk_data_wide = binary_data %>%
  select(ID, NOMTIME, PD = LIDV, BINARY_LEVELS) %>%
  right_join(pk_data %>% select(-BINARY_LEVELS), by = c("ID", "NOMTIME")) %>%
  rename(CONC = LIDV) %>%
  filter(!is.na(PD))

# Ordinal
ordinal_data <- pkpd_data %>%
  filter(CMT == ORDINAL_PD_CMT) %>%
  mutate(
    LIDV_jitter = jitter(LIDV, amount = 0.1),
    TIME_jitter = jitter(TIME, amount = 0.1*24))
# Ordinal PD vs PK
ordinal_pk_data_wide <- ordinal_data %>%
  select(ID, NOMTIME, PD = LIDV, ORDINAL_LEVELS, ORDINAL_LEVELS_low2high, ORDINAL_LEVELS_high2low) %>%
  right_join(pk_data %>% select(-ORDINAL_LEVELS, -ORDINAL_LEVELS_low2high, -ORDINAL_LEVELS_high2low), by = c("ID", "NOMTIME")) %>%
  rename(CONC = LIDV)%>%
  filter(!is.na(PD))%>%
  filter(!is.na(CONC))

# Count
count_data <- pkpd_data %>%
  filter(CMT == COUNT_PD_CMT) %>%
  mutate(count_low2high = factor(LIDV, levels = sort(unique(LIDV))),
         count_high2low = factor(LIDV, levels = rev(sort(unique(LIDV)))))
# Count PD vs PK
count_pk_data_wide = count_data %>%
  select(ID, NOMTIME, PD = LIDV) %>%
  right_join(pk_data) %>%
  rename(CONC = LIDV) %>%
  filter(!is.na(PD))%>%
  filter(!is.na(CONC))


# Noncompartmental Analysis (for additional plots)
NCA = pk_data %>%
  group_by(ID, DOSE) %>%
  filter(!is.na(LIDV)) %>%
  summarize(AUC_0 = ifelse(length(LIDV[NOMTIME > 0 & NOMTIME <= TAU]) > 1,
                              caTools::trapz(TIME[NOMTIME > 0 & NOMTIME <= TAU], 
                                      LIDV[NOMTIME > 0 & NOMTIME <= TAU]),
                              NA), 
            Cmax_0     = ifelse(length(LIDV[NOMTIME > 0 & NOMTIME <= TAU]) > 1,
                              max(LIDV[NOMTIME > 0 & NOMTIME <= TAU]),
                              NA), 
            AUC_tau = ifelse(length(LIDV[NOMTIME > (SS_PROFDAY-1)*24 & 
                                           NOMTIME <= ((SS_PROFDAY-1)*24 + TAU)]) > 1,
                             caTools::trapz(TIME[NOMTIME > (SS_PROFDAY-1)*24 & 
                                                   NOMTIME <= ((SS_PROFDAY-1)*24 + TAU)],
                                     LIDV[NOMTIME > (SS_PROFDAY-1)*24 & 
                                            NOMTIME <= ((SS_PROFDAY-1)*24 + TAU)]),
                             NA),
            Cmax_tau     = ifelse(length(LIDV[NOMTIME > (SS_PROFDAY-1)*24 & 
                                                NOMTIME <= ((SS_PROFDAY-1)*24 + TAU)]) > 1,
                             max(LIDV[NOMTIME > (SS_PROFDAY-1)*24 & 
                                        NOMTIME <= ((SS_PROFDAY-1)*24 + TAU)]),
                             NA), 
            SEX      = SEX[1], #this part just keeps the SEX and WEIGHTB covariates
            WEIGHTB  = WEIGHTB[1]) %>%
  gather(PARAM, VALUE, -c(ID, DOSE, SEX, WEIGHTB)) %>%
  ungroup() %>%
  mutate(VALUE_NORM = VALUE/DOSE,
         PROFDAY = ifelse(PARAM %in% c("AUC_0", "Cmax_0"), 1, SS_PROFDAY))

# Merge back with PD data
# Add response data at day 1 and at steady state to NCA for additional plots

# Continuous
continuous_NCA <- continuous_data %>% subset(PROFDAY %in% c(1, SS_PROFDAY),) %>%
                           select(ID, PROFDAY, DAY_label, PD = LIDV, TRTACT_low2high, TRTACT_high2low) %>%
                           merge(NCA, by = c("ID", "PROFDAY"))

# Binary
binary_NCA <- binary_data %>% subset(PROFDAY %in% c(1, SS_PROFDAY),) %>%
                           select(ID, PROFDAY, DAY_label, PD = LIDV, TRTACT_low2high, TRTACT_high2low) %>%
                           merge(NCA, by = c("ID", "PROFDAY"))

# Ordinal
ordinal_NCA <- ordinal_data %>% subset(PROFDAY %in% c(1, SS_PROFDAY),) %>%
                           select(ID, PROFDAY, DAY_label, PD = LIDV, TRTACT_low2high, TRTACT_high2low) %>%
                           merge(NCA, by = c("ID", "PROFDAY"))

# Count
count_NCA <- count_data %>% subset(PROFDAY %in% c(1, SS_PROFDAY),) %>%
                           select(ID, PROFDAY, DAY_label, PD = LIDV, TRTACT_low2high, TRTACT_high2low) %>%
                           merge(NCA, by = c("ID", "PROFDAY"))

#units and labels
time_units_dataset = "hours"
time_units_plot    = "days"
trtact_label       = "Dose"
time_label         = "Time(Days)"
dose_units         = unique((pkpd_data %>% filter(CMT == DOSE_CMT))$LIDV_UNIT) %>% as.character()
dose_label         = paste0("Dose (", dose_units, ")")
conc_units         = unique(pk_data$LIDV_UNIT) %>% as.character()
conc_label         = paste0("Concentration (", conc_units, ")")
AUC_units          = paste0("h.", conc_units)
concnorm_label     = paste0("Normalized Concentration (", conc_units, ")/", dose_units)
continuous_pd_units= unique(continuous_data$LIDV_UNIT) %>% as.character()
binary_pd_units    = unique(binary_data$LIDV_UNIT) %>% as.character()
ordinal_pd_units   = unique(ordinal_data$LIDV_UNIT) %>% as.character()
count_pd_units     = unique(count_data$LIDV_UNIT) %>% as.character()
continuous_label   = paste0("Continuous PD Marker (", continuous_pd_units, ")")  
binary_label       = "Response"
binary_response_label = paste0("Responder Rate (%)")
ordinal_label   = paste0("Ordinal PD Marker (", ordinal_pd_units, ")")
ordinal_response_label = paste0("Responder Rate (%)") 
count_label        = paste0("Count PD Marker (", count_pd_units, ")")
```


```{r child = 'overview.rmd'}
```

```{r child='available_datasets.rmd'}
```

```{r child='functions_overview.rmd'}
```

```{r child='functions_examples.rmd'}
```

```{r child='functions_exercises.rmd'}
```

```{r child='templates_overview.rmd'}
```

```{r child='templates_examples.rmd'}
```

```{r child='templates_autoexplore_example.rmd'}
```

```{r child='templates_autoexplore_exercise.rmd'}
```
