---
title: "Presentations and Publications"
output: 
  html_document:
    toc: true
    toc_float: true
---


* A. Margolskee, F. Khanshan, A. Stein, Y. Ho, M. Looby (2020) “Exploratory Graphics (xGx)”, part of “An open-source Pharmacometrician's workflow in R: from exploration (xGx) to model building (nlmixr) and diagnostics (ggPMX)”, Tutorial at ACoP11 2020 annual meeting, virtual ([video](SiteResources/2020_xgx_ACoP_tutorial.mp4)) 

* A. Margolskee, F. Khanshan, A. Stein, Y. Ho, M. Looby (2020), “Exploratory graphics (xGx) Cheat Sheet: promoting the purposeful exploration of PKPD data,” Poster at ACoP11 2020 annual meeting, virtual ([cheat sheet](Resources/PKPD_Exploratory_Graphics_(xGx)_Cheat_Sheet.pdf), [video](SiteResources/2020_xgx_ACoP_poster.mp4)) 

* F. Khanshan, A. Margolskee, A. Stein, Y. Ho, M. Looby (2019) “Exploratory Graphics (xGx)”, part of “An open-source Pharmacometrician's workflow in R: from exploration (xGx) to model building (nlmixr) and diagnostics (ggPMX)”, Tutorial at ACoP10 2019 annual meeting, Orlando, Florida 

* F. Khanshan, A. Margolskee, A. Stein, Y. Ho, M. Looby (2019) “Exploratory Graphics (xGx): Promoting the purposeful exploration of PKPD data”, Poster at ACoP10 2019 annual meeting, Orlando, Florida ([abstract](https://www.go-acop.org/assets/ACoP10/documents/ACoP10%20Combined%20Abstracts_2019.pdf#page=65)) 

* F. Khanshan, A. Margolskee, A. Stein, Y. Ho, M. Looby (2019) “Exploratory Graphics (xGx): Promoting the purposeful exploration of PKPD data”, Presentation at ACoP10 2019 annual meeting, Orlando, Florida ([abstract](https://www.go-acop.org/assets/ACoP10/documents/ACoP10%20Combined%20Abstracts_2019.pdf#page=65)) 
 
* A. Margolskee, F. Khanshan, A. Stein, Yu-Yun Ho, M. Looby (2019), “Exploratory Graphics (xGx) tool for purposeful PKPD data exploration”, Presentation at R/Pharma, August 2019, Harvard University, Massachusetts, USA

* A. Margolskee, F. Khanshan, A. Stein, Y. Ho, M. Looby (2019), “Exploratory graphics (xGx): promoting the purposeful exploration of PKPD data,” Presentation at 2019 PAGE annual meeting, Stockholm, Sweden ([abstract](https://www.page-meeting.org/default.asp?abstract=8913)) 

* U Minnesota Pharmacometrics Summer School (2019), One day training course on exploratory graphics - xGx, Minneapolis, MN 


