---
title: "Resources"
output: 
  html_document:
    toc: true
    toc_float: true
---

### Cheat sheets

* [xGx PKPD Cheat Sheet](Resources/PKPD_Exploratory_Graphics_(xGx)_Cheat_Sheet.pdf): 1-page front and back resource summarizing xGx principles, plots, and codes

* [R Best Practices](Resources/R PMX Best Practices Checklist v2 Public.pdf): 1-page reference sheet detailing some good practices for R coding, including tips for reproducibility and readability.

* [Graphics Principles Cheat Sheet](https://graphicsprinciples.github.io/cheatsheet.html): 1-page front and back cheat sheet summarizing good graphics principles ([PDF](https://github.com/GraphicsPrinciples/CheatSheet/blob/master/NVSCheatSheet.pdf))

* [Presentation Checklist](Resources/Presentation_Checklist_v2.03.pdf): 1 page checklist for planning, developing, and delivering presentations, focusing on effective communication.

* [Presentation Evaluation Form](Resources/Presentation_Evaluation_Form.doc): 1-page feedback form for evaluating presentations 
and/or asking for feedback.

* [Uncertainty Assessment - Pedigree Table](https://zenodo.org/record/4409236#.ZDm5J3fMKUl): 1-page reference sheet for evaluating the uncertainty of a model including quality of input data, breadth of exploration of model structure, incorporation of random effects, and predictive ability of model. ([PDF](https://zenodo.org/record/4409236/files/Uncertainty_Assessment_Pedigree_Table.pdf?download=1))

### Videos

* Effective Visual Communication (EVC) for the  Quantitative Scientist Cartoon Video ([video](https://graphicsprinciples.github.io/threelaws.html))

* xGx Tutorial Video, ACoP 2020 ([video](2020_xgx_ACoP_tutorial.html)) 

* xGx Cheat Sheet Video, ACoP 2020  ([video](2020_xgx_ACoP_poster.html)) 

### PK/PD Fundamentals trainings

* [Fundamental PK Principles Introduction](Resources/FundamentalPK_AndyStein_Hackathon_2019.pptx): Presentation of PK fundamentals targeted towards people with a quantitative background, but limited knowledge of PK.

* [Fundamental PD Principles Introduction](Resources/FundamentalPD_AndyStein_Hackathon_2019.pptx): Presentation of PD fundamentals targeted towards people with a quantitative background, but limited knowledge of PD.




### xGx Presentations and Publications

* A. Margolskee, F. Khanshan, A. M. Stein, Y. Ho, M. Looby (2020) “Exploratory Graphics (xGx)”, part of “An open-source Pharmacometrician's workflow in R: from exploration (xGx) to model building (nlmixr) and diagnostics (ggPMX)”, Tutorial at ACoP11 2020 annual meeting, virtual ([video](2020_xgx_ACoP_tutorial.html)) 

* A. Margolskee, F. Khanshan, A. M. Stein, Y. Ho, M. Looby (2020), “Exploratory graphics (xGx) Cheat Sheet: promoting the purposeful exploration of PKPD data,” Poster at ACoP11 2020 annual meeting, virtual ([cheat sheet](Resources/PKPD_Exploratory_Graphics_(xGx)_Cheat_Sheet.pdf), [video](2020_xgx_ACoP_poster.html)) 

* F. Khanshan, A. Margolskee, A. M. Stein, Y. Ho, M. Looby (2019) “Exploratory Graphics (xGx)”, part of “An open-source Pharmacometrician's workflow in R: from exploration (xGx) to model building (nlmixr) and diagnostics (ggPMX)”, Tutorial at ACoP10 2019 annual meeting, Orlando, Florida 

* F. Khanshan, A. Margolskee, A. M. Stein, Y. Ho, M. Looby (2019) “Exploratory Graphics (xGx): Promoting the purposeful exploration of PKPD data”, Poster at ACoP10 2019 annual meeting, Orlando, Florida ([abstract](https://www.go-acop.org/assets/ACoP10/documents/ACoP10%20Combined%20Abstracts_2019.pdf#page=65)) 

* F. Khanshan, A. Margolskee, A. M. Stein, Y. Ho, M. Looby (2019) “Exploratory Graphics (xGx): Promoting the purposeful exploration of PKPD data”, Presentation at ACoP10 2019 annual meeting, Orlando, Florida ([abstract](https://www.go-acop.org/assets/ACoP10/documents/ACoP10%20Combined%20Abstracts_2019.pdf#page=65)) 
 
* A. Margolskee, F. Khanshan, A. M. Stein, Yu-Yun Ho, M. Looby (2019), “Exploratory Graphics (xGx) tool for purposeful PKPD data exploration”, Presentation at R/Pharma, August 2019, Harvard University, Massachusetts, USA

* A. Margolskee, F. Khanshan, A. M. Stein, Y. Ho, M. Looby (2019), “Exploratory graphics (xGx): promoting the purposeful exploration of PKPD data,” Presentation at 2019 PAGE annual meeting, Stockholm, Sweden ([abstract](https://www.page-meeting.org/default.asp?abstract=8913)) 

* U Minnesota Pharmacometrics Summer School (2019), One day training course on exploratory graphics - xGx, Minneapolis, MN 

        
        
