---
title: "Tutorial for the xGx package"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  learnr::tutorial:
    progressive: True
    allow_skip: False
  html_document:
    toc: true
    toc_float: true
    include:
      in_header: ./SiteResources/header.html
      before_body: ./SiteResources/body.html
    lib_dir: site_libs
    self_contained: no

runtime: shiny_prerendered
description: >
  Learn how to create exploratory plots of PKPD data
  using the xGx package functions
  
name: Exploratory Plots
output_dir: www
include: '*.html'
navbar:
  title: xGx
  type: inverse
  left:
  - icon: glyphicon-home
    href: index.html
  - text: Guiding Principles
    href: GuidingPrinciples.html
  - text: Data Checking
    menu:
    - text: Dataset Specifications
      href: Datasets.html
    - text: Master PK/PD Datasets used in creating example plots
      href: PKPD_Datasets.html
    - text: Data Checking
      href: Data_Checking.html
  - text: Dose-PK/Exposure
    src: PD_icon.png
    menu:
    - text: Single Ascending Dose - PK
      href: Single_Ascending_Dose_PK.html
    - text: Multiple Ascending Dose - PK
      href: Multiple_Ascending_Dose_PK.html
    - text: Example using realistic data
      href: Multiple_Ascending_Dose_PK_KeyPlots.html
  - text: Dose-PD/Efficacy/Safety
    menu:
    - text: Continuous
      href: Multiple_Ascending_Dose_PD_continuous.html
    - text: Binary Response
      href: Multiple_Ascending_Dose_PD_binary.html
    - text: Ordinal Response
      href: Multiple_Ascending_Dose_PD_ordinal.html
    - text: Count Data
      href: Multiple_Ascending_Dose_PD_count.html
    - text: Time to Event
      href: Multiple_Ascending_Dose_PD_time_to_event.html
    - text: Oncology Efficacy Endpoints (RECIST)
      href: Oncology_Efficacy_Plots.html
    - text: PD/Efficacy Example using realistic data
      href: Multiple_Ascending_Dose_PD_real_example.html
  - text: PK-PD/Efficacy/Safety
    menu:
    - text: Continuous
      href: Multiple_Ascending_Dose_PKPD_continuous.html
    - text: Binary Response
      href: Multiple_Ascending_Dose_PKPD_binary.html
    - text: Ordinal Response
      href: Multiple_Ascending_Dose_PKPD_ordinal.html
    - text: Count Data
      href: Multiple_Ascending_Dose_PKPD_count.html
    - text: Time to Event
      href: Multiple_Ascending_Dose_PKPD_time_to_event.html
    - text: Adverse Events
      href: Adverse_Events.html
  - text: Resources
    menu:
      - text: PKPD Cheat Sheet
        href: Resources/PKPD_Exploratory_Graphics_(xGx)_Cheat_Sheet.pdf
      - text: Graphics Principles Cheat Sheet
        href: Resources/Graphics_Principles_Cheat_Sheet_v1.1.pdf
      - text: Fundamental PK Principles Introduction
        href: Resources/FundamentalPK_AndyStein_Hackathon_2019.pptx      
      - text: Fundamental PD Principles Introduction
        href: Resources/FundamentalPD_AndyStein_Hackathon_2019.pptx 
      - text: Presentation Checklist
        href: Resources/Presentation_Checklist_v2.03.pdf
      - text: Uncertainty Assessment - Pedigree Table
        href: Resources/Uncertainty_Assessment_Pedigree_Table.pdf
---

```{r setup, include=FALSE}
library(learnr)
library(tidyverse)
library(xgxr)
library(DescTools)
library(minpack.lm)

source("https://raw.githubusercontent.com/Novartis/xgxr/master/R/xgx_stat_ci.R")
source("https://raw.githubusercontent.com/Novartis/xgxr/master/R/xgx_stat_smooth.R")
source("https://raw.githubusercontent.com/Novartis/xgxr/master/R/xgx_auto_explore.R")

tutorial_options(exercise.timelimit = 60)
knitr::opts_chunk$set(error = TRUE)

# ggplot settings
xgx_theme_set()




pkpd_data <- read.csv("https://raw.githubusercontent.com/Novartis/xgx/master/Data/Multiple_Ascending_Dose_Dataset2.csv")

DOSE_CMT = 1
PK_CMT = 2
PD_CMT = 5
SS_PROFDAY = 6 # steady state prof day
PD_PROFDAYS <- c(0, 2, 4, 6)
TAU = 24 # time between doses, units should match units of TIME, e.g. 24 for QD, 12 for BID, 7*24 for Q1W (when units of TIME are h)

#ensure dataset has all the necessary columns
pkpd_data = pkpd_data %>%
  mutate(ID = ID,
         TIME = TIME,
         NOMTIME = NOMTIME,
         PROFDAY = 1 + floor(NOMTIME / 24),
         LIDV = LIDV,
         CENS = CENS,
         CMT = CMT,
         DOSE = DOSE,
         TRTACT = TRTACT,
         LIDV_NORM = LIDV/DOSE,
         LIDV_UNIT = EVENTU,
         DAY_label = ifelse(PROFDAY > 0, paste("Day", PROFDAY), "Baseline"),
         ORDINAL_LEVELS = factor(case_when(CMT != PD_CMT ~ as.character(NA),
                                           LIDV == 1 ~ "Mild",
                                           LIDV == 2 ~ "Moderate",
                                           LIDV == 3 ~ "Severe"),
                                 levels = c("Mild", "Moderate", "Severe"))
         )

#create a factor for the treatment variable for plotting
pkpd_data = pkpd_data %>%
  arrange(DOSE) %>%
  mutate(TRTACT_low2high      = factor(TRTACT, levels = unique(TRTACT)),
         TRTACT_high2low      = factor(TRTACT, levels = rev(unique(TRTACT))),
         ORDINAL_LEVELS_low2high    = ORDINAL_LEVELS,
         ORDINAL_LEVELS_high2low    = factor(ORDINAL_LEVELS, levels = rev(levels(ORDINAL_LEVELS))))

#create pk and pd datasets
pk_data <- pkpd_data %>%
  filter(CMT == PK_CMT)

pd_data <- pkpd_data %>%
  filter(CMT == PD_CMT) %>%
  mutate(
    LIDV_jitter = jitter(LIDV, amount = 0.1),
    TIME_jitter = jitter(TIME, amount = 0.1*24)
        )

#create wide pkpd dataset for plotting PK vs PD
pkpd_data_wide <- pd_data %>%
  select(ID, NOMTIME, PD = LIDV, ORDINAL_LEVELS, ORDINAL_LEVELS_low2high, ORDINAL_LEVELS_high2low) %>%
  right_join(pk_data %>% select(-ORDINAL_LEVELS, -ORDINAL_LEVELS_low2high, -ORDINAL_LEVELS_high2low), by = c("ID", "NOMTIME")) %>%
  rename(CONC = LIDV)%>%
  filter(!is.na(PD))%>%
  filter(!is.na(CONC))

#units and labels
time_units_dataset = "hours"
time_units_plot    = "days"
trtact_label       = "Dose"
time_label         = "Time(Days)"
dose_units         = unique((pkpd_data %>% filter(CMT == DOSE_CMT))$LIDV_UNIT) %>% as.character()
dose_label         = paste0("Dose (", dose_units, ")")
conc_units         = unique(pk_data$LIDV_UNIT) %>% as.character()
conc_label         = paste0("Concentration (", conc_units, ")")
AUC_units          = paste0("h.", conc_units)
concnorm_label     = paste0("Normalized Concentration (", conc_units, ")/", dose_units)
pd_units           = unique(pd_data$LIDV_UNIT) %>% as.character()
pd_response_label  = "Responder Rate (%)"
pd_ordinal_label   = paste0("Ordinal PD Marker (", pd_units, ")")
```


```{r child = 'overview.rmd'}
```

```{r child='data_checking.rmd'}
```

```{r child='functions_overview.rmd'}
```

```{r child='functions_examples.rmd'}
```

```{r child='functions_exercises.rmd'}
```

```{r child='templates_overview.rmd'}
```

```{r child='templates_examples.rmd'}
```

```{r child='templates_exercises.rmd'}
```

```{r child='templates_autoexplore_example.rmd'}
```

```{r child='templates_autoexplore_exercise.rmd'}
```
